### ISSUE TITLE
Outcome configuration UI

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-web-app#1075]
# Step 0 -- rename/consolidate outcomes and lookup tables

"Outcomes" is poorly named and should be changed ASAP. I think we agreed on "data" or "database", but can continue to discuss.

I suggest that lookup table and outcome table names should share a common prefix, as there's not really a reason to distinguish between them. So they can all become "data_<name>". Also, we should register new outcome "data" tables in the (currently) "lookup_table" table similar to lookup tables so the system can have a better way to keep track of its data.

So that would be:
- rename "lookup_table" to "data_table"
- update the "modifyRecord" action -> "createTable" method to also register the table in "data_table" on creation (and also: add a field to "data_table" called "is_lookup_table", so we have a way to keep track of which is which -- the only real difference would be that lookup tables can be exported/imported using the Lookup table UI, whereas "normal" data tables can't be)
- write migration code (back-end SQL?) to change existing snapshots when first launched
- add the prefix "data_" to all new tables created with modifyRecord or lookup table import

# Step 0.5 Fix lookup tables

They're currently quite broken. Also, they don't handle types other than strings. I actually think we can use the modifyRecord action as the data writing module, since it's already built to handle table creation, type detection and data entry. Presumably it will be fine to use it it iterate over hundreds of records when inserting. I think this will be easier and more useful ultimately than trying to fix the existing import routine.

# Step 1 -- link Data tables to Templates

- Add  "template_id"  field to "outcome_display" table (should be optional as outcomes shouldn't *have* to be linked to templates, and in many cases won't be.
- Update "outcomes" endpoints to filter outcomes to only return the ones that are connected to template versions that are "active", or have no template_id
- Export/import linked outcome records with template import/export

# Step 2 -- UI

It occurs to me that the Outcome configurations themselves can be just displayed as "Outcomes" themselves -- so the "display" side of this is already done! (~~I'll quickly whip up a demo and add it to core templates~~ Demo available in snapshot: `.../application-manager-templates/dev/snapshots/core_templates_outcomes_demo`)

As far as the editing side of things goes, the [proposal for editing lookup tables](https://github.com/openmsupply/application-manager-server/issues/629) pretty much applies here too. So if we do that work, then we've pretty much got outcome configuration for free. There'll be some specific requirements for how to edit some of the more fiddly columns, but in essence it should basically work the same.

**Update**: This is not *entirely* true. What I said applies to the "outcome_display", but it won't automatically apply to the "outcome_display_column_definition" table, that would require additional development (since outcomes/lookup-tables assume a single table of data)

**Comment by nmadruga** [comment]
Minutes meeting
* Using prefix of "data_" on imported tables would amek it clear about which ones are core and the ones that are added in this configuration. Also to remove the wording `outcomes`. 
  * Should we add `product` or `license` tables as part of the core. No, because they are not exactly core.
* The `data_table` idea seems good. Perhaps a different name.
* Tricky to write migration code for existing snapshots with no-prefixed outcomes tables
* Replace the 
  * Does the job for checking types already
  * Doesn't establish the primary key though - can do it using "modifyRecord"
  * Maybe we should move "modifyRecord" from the action to be a core function that gets used by an action 
* The link to a template would also helpt when exporting and importing the template to already come with lookup tables associated. We should allow for outcomes to be re-imported (for editing) or even exported.
* Rename `outcomes_display` to `data_view`
* When we create a new version of a template what should we do about all the `data_view` and `data_view_details` records. Duplicate or just point to the latest version? Seems better to duplicate because there could be changes to the view and details config.
  * So that's why it's needed to filter for only `active` ones to be fetched on the outcomes/endpoint
  * Just check that on the endpoint (which ones are linked to the active version of the template)
* "Data views" or "View data" on the UI if better than outcomes
* We have 2 concepts to be improved related to the old `outcomes` (to be rename to data_view) basically how to edit the lookup table data and how to edit the layout for data_view_details.
* After a new outcome is create do we create a new `data_view`? No. But if this was automatic how to select the default fields to diplay on the data_view list

**Comment by nmadruga** [comment]
Hmmm I see that this has slipped our vision when planning for Phase too deliverables. Well, it hasn't been considered, since for now updating the Lookup tables is good for the momment.

Just a comment, I can see the decision at least the recorded here was to rename to `data_view` instead `data_displays`, which matches what I have suggested on the PR review.
