### ISSUE TITLE
Bug: Reviewer can self-assign after applicant has re-submitted to LOQ

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1195]
To reproduce this problem:
- Application is put into 'request clarification (List of Questions)' state by User 1
- Appears to User 2 as self-assignable and can self-assign it

See Adam for more details (posted on Subforma on 10th May 2022)

**Comment by adamdewey** [comment]
Actually the issue here isn't after the applicant has re-submitted to the LOQ, but _before_. 

Reviewer 1 has sent the LOQ to the applicant. 

While the application is sitting with the applicant Reviewer 2 can see the application as self-assignable. 

Reviewer 2 shouldn't be able to see this, their dashboard should appear the same as Reviewer 1 (where the application is hidden from the dashboard and is un-self-assignable until the applicant has re-submitted the application). 

I'll try and get some screenshots up when I get a chance

**Comment by adamdewey** [comment]
Ok here you go: 

![image](https://user-images.githubusercontent.com/19318937/168044685-7a5eccce-793e-405a-9f49-8cc8f06d9462.png)

![image](https://user-images.githubusercontent.com/19318937/168044704-8402fed2-337d-4fd8-81b6-1f536b6eb169.png)

![image](https://user-images.githubusercontent.com/19318937/168044725-f8747810-ba34-4cf6-bf54-2aa5bcf2c265.png)

![image](https://user-images.githubusercontent.com/19318937/168044748-fdc2ded9-9a72-47ea-94bb-7a780c453e1f.png)

![image](https://user-images.githubusercontent.com/19318937/168044773-85f92e18-4a62-42d8-bacc-1cac8a3ee26d.png)
