### ISSUE TITLE
Fiji testing day - Bouncing router on Application summary page

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1416]
1. "Had a routing issue, not sure if i can reproduce (will try), i stayed on the submitted page, and the reviewed it and made LOQ, then from submitted page pressed view submited application and then router were bouncing between summary and application home page, works fine after refresh" 
by Andrei 
Note for Jess: Need to reword... Can be reproduced

**Comment by CarlosNZ** [comment]
I've fixed it before, I can fix it again.... 🙄

**Comment by CarlosNZ** [comment]
Okay, just chatted to Andrei about this -- turns out it just an edge case. It only happens when the applicant has submitted and then a reviewer reviews and submits their review in another browser, then the original applicant tries to go to back to the application summary page you get the problem. And it goes away after a refresh.

So very edge case (how many people are going to sit there on the summary page while their reviewer does their whole review?)

I think it gets caused due to an inconsistent state -- something will be being refreshed but not something else. But I don't think we need to fix this now, as it'll probably get taken care of as part of wider state-management improvements in the future.
