### ISSUE TITLE
Fiji testing day - Problem parsing activity log event for Assignment

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1418]
![Image](https://user-images.githubusercontent.com/16461988/199635649-44b77199-f36b-475b-b224-1405d4e4325f.png)

**Comment by CarlosNZ** [comment]
I'm hoping this is connected to #947. 

If there's something misconfigured there, then an Action probably failed. In which case that would also cause this problem for the assignment, since the activity log would be referring to events that don't have a proper record created.

In other words, fix #947 first and I think (hope 🤞) this one will go away ;)
